import os
import json
import requests

OLLAMA_ENDPOINT = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3.2:3b"

# 20 adapted queries from technical/Ubuntu dialogue style to e-commerce customer support
queries = [
    "How do I check the shipping status of my recent order?",
    "My discount code is not working at checkout.",
    "Can I change my shipping address after placing an order?",
    "How do I return a pair of shoes that don't fit?",
    "I received a damaged item, what should I do?",
    "Why was my credit card declined during payment?",
    "How do I delete my account and remove my personal data?",
    "Do you offer international shipping to Europe?",
    "Can I combine two separate orders to save on shipping?",
    "How do I update my email address in my account profile?",
    "Where can I find the invoice for my order?",
    "My order is marked as delivered, but I haven't received it.",
    "How long does it take to process a refund?",
    "Can I pre-order an item that is currently out of stock?",
    "How do I reset my account password?",
    "Is there a discount code for my first purchase?",
    "Do you have a physical store where I can try on clothes?",
    "How do I apply a gift card to my order?",
    "The price of an item dropped after I bought it, can I get a price match?",
    "How do I contact customer support by phone?"
]

def query_ollama(prompt):
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False
    }
    try:
        response = requests.post(OLLAMA_ENDPOINT, json=payload, timeout=60)
        response.raise_for_status()
        result_json = response.json()
        return result_json.get("response", "").strip()
    except requests.exceptions.RequestException as e:
        print(f"Error querying Ollama: {e}")
        return f"Error: Could not get a response from the model. Details: {e}"

def main():
    # Read templates
    zero_shot_template_path = os.path.join("prompts", "zero_shot_template.txt")
    one_shot_template_path = os.path.join("prompts", "one_shot_template.txt")

    with open(zero_shot_template_path, "r", encoding="utf-8") as f:
        zero_shot_template = f.read()

    with open(one_shot_template_path, "r", encoding="utf-8") as f:
        one_shot_template = f.read()

    # Create directories if not exists
    os.makedirs("eval", exist_ok=True)
    results_path = os.path.join("eval", "results.md")

    # Start writing the results file
    with open(results_path, "w", encoding="utf-8") as f:
        f.write("# Chatbot Evaluation Results\n\n")
        f.write("This file logs the responses generated by Llama 3.2 3B using Zero-Shot and One-Shot prompting methods. Each response must be evaluated on a scale of 1-5 for Relevance, Coherence, and Helpfulness.\n\n")
        f.write("### Scoring Rubric\n")
        f.write("- **Relevance (1-5)**: How well does the response address the customer's query? (1 = Irrelevant, 5 = Perfectly relevant)\n")
        f.write("- **Coherence (1-5)**: Is the response grammatically correct and easy to understand? (1 = Incoherent, 5 = Flawless)\n")
        f.write("- **Helpfulness (1-5)**: Does the response provide a useful, actionable answer? (1 = Not helpful, 5 = Very helpful)\n\n")
        f.write("| Query # | Customer Query | Prompting Method | Response | Relevance (1-5) | Coherence (1-5) | Helpfulness (1-5) |\n")
        f.write("| --- | --- | --- | --- | --- | --- | --- |\n")

    print(f"Starting queries to local Llama 3.2 model. Results will be saved in: {results_path}")

    for idx, query in enumerate(queries, 1):
        print(f"Processing Query {idx}/20: '{query}'")

        # 1. Zero-Shot
        zero_shot_prompt = zero_shot_template.replace("{query}", query)
        print("  - Running Zero-Shot...")
        zero_shot_resp = query_ollama(zero_shot_prompt)
        # Escape newlines and pipes for markdown table
        zero_shot_resp_clean = zero_shot_resp.replace("\n", " ").replace("|", "\\|")

        # 2. One-Shot
        one_shot_prompt = one_shot_template.replace("{query}", query)
        print("  - Running One-Shot...")
        one_shot_resp = query_ollama(one_shot_prompt)
        # Escape newlines and pipes for markdown table
        one_shot_resp_clean = one_shot_resp.replace("\n", " ").replace("|", "\\|")

        # Append to results file
        with open(results_path, "a", encoding="utf-8") as f:
            f.write(f"| {idx} | {query} | Zero-Shot | {zero_shot_resp_clean} |  |  |  |\n")
            f.write(f"| {idx} | {query} | One-Shot | {one_shot_resp_clean} |  |  |  |\n")

    print("Finished querying. Please proceed to manually grade the responses in eval/results.md.")

if __name__ == "__main__":
    main()
